Updated configure script
svn: r1170

diff --git a/gramps2/configure b/gramps2/configure
--- a/gramps2/configure
+++ b/gramps2/configure
@@ -1441,7 +1441,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=gramps
- VERSION=0.9.0pre2
+ VERSION=0.9.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -1567,7 +1567,7 @@ INSTALL_STRIP_PROGRAM="\${SHELL} \$(install_sh) -c -s"
 
 
 
-RELEASE=rc4
+RELEASE=pre3
 
 VERSIONSTRING=$VERSION
 if test x"$RELEASE" != "x"
@@ -3638,44 +3638,6 @@ GNOMEINC=`pkg-config --cflags gnome-vfs-module-2.0`
 GNOMELIB=`pkg-config --libs gnome-vfs-module-2.0`
 
 
-echo "$as_me:$LINENO: checking Python bindings for sax/xml" >&5
-echo $ECHO_N "checking Python bindings for sax/xml... $ECHO_C" >&6
-
-cat > conftest.py <<EOF
-try:
-    from xml.sax import make_parser, handler
-    f = open("conftest.out", "w")
-    f.write("YES")
-    f.close()
-except ImportError:
-
-    try:
-        from _xmlplus.sax import make_parser, handler
-        f = open("conftest.out", "w")
-        f.write("YES")
-        f.close()
-    except ImportError:
-        f = open("conftest.out", "w")
-        f.write("NO")
-        f.close()
-EOF
-
-$PYTHON conftest.py
-has_sax=`cat conftest.out`
-rm -f conftest.out conftest.py
-if test "YES" != $has_sax
-then
-   { { echo "$as_me:$LINENO: error:
-
-**** The python interpreter can't find the SAX/XML bindings." >&5
-echo "$as_me: error:
-
-**** The python interpreter can't find the SAX/XML bindings." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-echo "$as_me:$LINENO: result: ok" >&5
-echo "${ECHO_T}ok" >&6
-
 echo "$as_me:$LINENO: checking Python bindings for gtk" >&5
 echo $ECHO_N "checking Python bindings for gtk... $ECHO_C" >&6
 
@@ -3698,10 +3660,10 @@ if test "YES" != $has_pygtk
 then
    { { echo "$as_me:$LINENO: error:
 
-**** The python interpreter can't find the python bindings for gtk 2.0." >&5
+**** The python bindings for gtk 2.0 (pygtk2) could not be found." >&5
 echo "$as_me: error:
 
-**** The python interpreter can't find the python bindings for gtk 2.0." >&2;}
+**** The python bindings for gtk 2.0 (pygtk2) could not be found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 echo "$as_me:$LINENO: result: ok" >&5
@@ -3728,40 +3690,9 @@ rm -f conftest.out conftest.py
 if test "YES" != $has_pygnome
 then
    { { echo "$as_me:$LINENO: error:
-**** The python interpreter can't find the python bindings for GNOME." >&5
+**** The python bindings for GNOME 2.0 (gnome-python2) could not be found." >&5
 echo "$as_me: error:
-**** The python interpreter can't find the python bindings for GNOME." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-echo "$as_me:$LINENO: result: ok" >&5
-echo "${ECHO_T}ok" >&6
-
-echo "$as_me:$LINENO: checking Python/libglade bindings" >&5
-echo $ECHO_N "checking Python/libglade bindings... $ECHO_C" >&6
-
-cat > conftest.py <<EOF
-try:
-    import gtk.glade
-    f = open("conftest.out", "w")
-    f.write("YES")
-    f.close()
-except ImportError:
-    f = open("conftest.out", "w")
-    f.write("NO")
-    f.close()
-EOF
-
-$PYTHON conftest.py
-has_pygtk=`cat conftest.out`
-rm -f conftest.out conftest.py
-if test "YES" != $has_pygtk
-then
-   { { echo "$as_me:$LINENO: error:
-
-**** The python interpreter can't find the python bindings for libglade." >&5
-echo "$as_me: error:
-
-**** The python interpreter can't find the python bindings for libglade." >&2;}
+**** The python bindings for GNOME 2.0 (gnome-python2) could not be found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 echo "$as_me:$LINENO: result: ok" >&5
@@ -3788,11 +3719,69 @@ rm -f conftest.out conftest.py
 if test "YES" != $has_gconf
 then
    { { echo "$as_me:$LINENO: error:
+**** The python bindings for gconf (gnome-python2-gconf) could not be found." >&5
+echo "$as_me: error:
+**** The python bindings for gconf (gnome-python2-gconf) could not be found." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
 
-**** The python interpreter can't find the python bindings for gconf." >&5
+echo "$as_me:$LINENO: checking Python bindings for GNOME canvas" >&5
+echo $ECHO_N "checking Python bindings for GNOME canvas... $ECHO_C" >&6
+
+cat > conftest.py <<EOF
+try:
+    import gnome.canvas
+    f = open("conftest.out", "w")
+    f.write("YES")
+    f.close()
+except ImportError:
+    f = open("conftest.out", "w")
+    f.write("NO")
+    f.close()
+EOF
+
+$PYTHON conftest.py
+has_canvas=`cat conftest.out`
+rm -f conftest.out conftest.py
+if test "YES" != $has_canvas
+then
+   { { echo "$as_me:$LINENO: error:
+**** The python bindings for GNOME canvas (gnome-python2-canvas) could not be found." >&5
+echo "$as_me: error:
+**** The python bindings for GNOME canvas (gnome-python2-canvas) could not be found." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+
+echo "$as_me:$LINENO: checking Python bindin for glade" >&5
+echo $ECHO_N "checking Python bindin for glade... $ECHO_C" >&6
+
+cat > conftest.py <<EOF
+try:
+    import gtk.glade
+    f = open("conftest.out", "w")
+    f.write("YES")
+    f.close()
+except ImportError:
+    f = open("conftest.out", "w")
+    f.write("NO")
+    f.close()
+EOF
+
+$PYTHON conftest.py
+has_pygtk=`cat conftest.out`
+rm -f conftest.out conftest.py
+if test "YES" != $has_pygtk
+then
+   { { echo "$as_me:$LINENO: error:
+
+**** The python bindings for glade (pytgk2-libglade) could not be found." >&5
 echo "$as_me: error:
 
-**** The python interpreter can't find the python bindings for gconf." >&2;}
+**** The python bindings for glade (pytgk2-libglade) could not be found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 echo "$as_me:$LINENO: result: ok" >&5
